services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - LANG=es_CL.UTF-8
      - LC_ALL=es_CL.UTF-8
    depends_on:
      - db

  db:
    image: postgres-escl
    environment:
      POSTGRES_INITDB_ARGS: "--locale-provider=libc --locale=es_CL.UTF-8 --encoding=UTF8"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
      LANG: es_CL.UTF-8
      LC_ALL: es_CL.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - pgdata16:/var/lib/postgresql/data

volumes:
  pgdata16: