services:
  app:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/attendance
      - LANG=es_CL.UTF-8
      - LC_ALL=es_CL.UTF-8
    depends_on:
      - db
    restart: always

  db:
    image: postgres:bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance
    ports:
      - "5432:5432"
    volumes:
      - pgdata16:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata16: